Created installation.txt
deviceinsight/csbootstrap pull request #6
Opened 2019-10-01 12:06 UTC by LakshitF

Moved the development section to installation.txt as requested.

2019-10-02 14:40 UTC, s-spindler commented
@LakshitF Thanks for the contribution! Can you please change the file name to DEVELOPMENT.md? Also, the section should then be removed from the README.md.

2019-10-14 08:22 UTC, s-spindler commented
@LakshitF Sorry for late feedback; can you please also implement the other feedback suggestions?

2019-10-14 08:40 UTC, LakshitF commented
Have done.

On Mon, 14 Oct 2019, 13:53 Stephan Spindler, <notifications@github.com>
wrote:

> @LakshitF <https://github.com/LakshitF> Sorry for late feedback; can you
> please also implement the other feedback suggestions?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/deviceinsight/csbootstrap/pull/6?email_source=notifications&email_token=AGY3USLPLENESIFKOTCE6L3QOQT6HA5CNFSM4I4ISHQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBDWFDA#issuecomment-541549196>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGY3USKSAPTCCFYDSN3CYFDQOQT6HANCNFSM4I4ISHQA>
> .
>

2019-10-14 11:13 UTC, s-spindler requested changes

2019-10-14 11:13 UTC, s-spindler commented on installation.txt
> +
Maybe super nitpicky, but the second empty line is redundant.

2019-10-14 11:13 UTC, s-spindler commented on installation.txt
> +## Development
Since this is now a separate file, it should be a level 1 header, so only one `#`.

2019-10-14 11:17 UTC, s-spindler commented
@LakshitF Sorry, I hadn't submitted the review :( Please see above...

2020-10-01 07:09 UTC, closed without merging